name: test
on:
  push:

jobs:
  call-own-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        octokit-core-version: ["4.2.4", "5.0.0"]
    steps:
      - uses: actions/checkout@v3

      - name: Override octokit/core version and install deps
        run: npm i --save-exact "@octokit/core@${{ matrix.octokit-core-version }}"
      - name: Rebundle own action
        run: npm run bundle

      - name: Run own action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
